set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim

"
" Toda lista de plugins deve ser colocada ENTRE os comandos begin() e end()
"
call vundle#begin()

" Vundle se auto-gerencia
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'                    " Exibe a arvore de diretorios 
Plugin 'mustache/vim-mustache-handlebars'       " syntax highlight para mustache / handlebars
Plugin 'ervandew/supertab'                      " Tab completion
Plugin 'jnurmine/Zenburn'                       " Tema
Plugin 'nathanaelkane/vim-indent-guides'        " Exibe linhas de identacao
Plugin 'taglist.vim'                            " Source code browser (Pre-requisito: instalar ctags)
Plugin 'tpope/vim-fugitive'                     " Git wrapper para vim
Plugin 'Lokaltog/vim-easymotion'                " Facil navegacao entre palavras
Plugin 'bufexplorer.zip'                        " Atalhos para navegacao entre buffers
Plugin 'kien/ctrlp.vim'                         " Um finder melhorado para o vim.
"Plugin 'SirVer/ultisnips'                       " Code snippets
"Plugin 'honza/vim-snippets'                     " Snippets are separated from the engine.
Plugin 'tpope/vim-vividchalk'                   " Tema
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-markdown'
Plugin 'evgenyzinoviev/vim-vendetta'

call vundle#end()
filetype plugin indent on

syntax on
set number
set backspace=2
set backspace=indent,eol,start

" Color Scheme, identation, etc
set t_Co=256
colors vendetta
set ts=2 sw=2 et
let g:indent_guides_auto_colors=0
autocmd VimEnter,ColorScheme * :hi IndentGuidesOdd guibg=black ctermbg=235
autocmd VimEnter,ColorScheme * :hi IndentGuidesEven guibg=darkgrey ctermbg=237
let g:indent_guides_start_level=1
let g:indent_guides_guide_size=1
let g:indent_guides_enable_on_vim_startup=1 "enable on startup

" recognize json files with javascript syntax
autocmd BufNewFile,BufRead *.json set ft=javascript

"
" taglist
"
let Tlist_Use_Right_Window = 1

"
" Airline
"
set laststatus=2
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'

let g:airline_symbols = {}
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" 
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline#extensions#tabline#enabled = 1

"
" Atalhos
"

"### Atalhos com CTRL
"# Ctrl + n: Ativa a NERDTree
map <C-n> :NERDTreeToggle<CR>
"# Ctrl + i: Ativa a identacao
map <C-i> :IndentGuidesToggle<CR>

"### Atalhos com SHIFT
"# Shift + Left: Avanca para a aba esquerda
map <S-Left> gT
"# Shift + Right: Avanca para a aba direita
map <S-Right> gt

"### Outros atalhos
map <C-T> :TlistToggle<CR>
