#!/bin/bash
##
# Arquivo: backup
# Description: Backup and restore functions
# Since: 21/02/2013
#
#  This file is free software: you may copy, redistribute and/or modify it  
#  under the terms of the GNU General Public License as published by the  
#  Free Software Foundation, either version 2 of the License, or (at your  
#  option) any later version.  
#  
#  This file is distributed in the hope that it will be useful, but  
#  WITHOUT ANY WARRANTY; without even the implied warranty of  
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  
#  General Public License for more details.  
#  
#  You should have received a copy of the GNU General Public License  
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
##

#
# backup()
# @param $1: Parent folder for backup
#
backup(){
	DATETAG=$(date +%d-%m-%Y)		
	
	BACKUP_PARENT_FOLDER="$1"
	SRC="/*"
	SNAP="$BACKUP_PARENT_FOLDER/latest"	
	BKP_FOLDER="$BACKUP_PARENT_FOLDER/$DATETAG"
	OPTS="-aAXv --link-dest=$SNAP --exclude=/dev --exclude=/proc --exclude=/sys --exclude=/tmp --exclude=/run --exclude=/mnt --exclude=/media --exclude=/lost+found --exclude=/home/*/.gvfs"
	
	
	
	# if the rsync is not installed, exit
	if [ ! -f /usr/bin/rsync ] ; then
		log "backup" "rsync must be installed on the system\n"
		return 1
	fi
	
	
	# run this process with low priority
	ionice -c 3 -p $$
	renice +12 -p $$
	# create the folder if don't exist:
	if [ ! -d "$BACKUP_PARENT_FOLDER" ] ; then
		mkdir -p $BACKUP_PARENT_FOLDER
	fi

	#sync
	log "backup" "**** Backup:"
	START=$(date +%s)
	rsync $OPTS $SRC $BKP_FOLDER
	rm -f $SNAP
	ln -s $BKP_FOLDER $SNAP	
	FINISH=$(date +%s)
	
	log "backup" "** Backup of $DATETAG: $(( ($FINISH-$START) / 60  )) minutes, $((  ($FINISH-$START) % 60 )) seconds\n"
}

##
# restore()
# @param $1 Folder for restore
##
restore(){
	DATETAG=$(date +%d-%m-%Y)
	LOG_FOLDER="$LOG_FOLDER/restore"
	

	# if the log folder don't exist, create
	if [ ! -d $LOG_FOLDER ] ; then		
		mkdir -p $LOG_FOLDER
	fi
	
	# if the rsync is not installed, exit
	if [ ! -f /usr/bin/rsync ] ; then
		log "backup" "rsync must be installed on the system"
		exit 1
	fi
	
	log "restore" "Not implemented yet."
}
