#!/bin/sh

##
# git configs
##
git config --global user.name "Giovane Boaviagem"
git config --global user.email "giovanebribeiro@gmail.com"
ln -s $PWD/git_templates $HOME/.git_templates
git config --global init.templatedir '~/.git_templates'
git config --global alias.ctags '!.git/hooks/ctags'
ln -s $PWD/ctags_configs $HOME/.ctags
