#!/bin/bash

##
# File: toolbox
# Author: Giovane Boaviagem <giovanebribeiro@gmail.com>
# Description: Toolbox for arch linux servers
# Since: 21/02/2013
#
#  This file is free software: you may copy, redistribute and/or modify it  
#  under the terms of the GNU General Public License as published by the  
#  Free Software Foundation, either version 2 of the License, or (at your  
#  option) any later version.  
#  
#  This file is distributed in the hope that it will be useful, but  
#  WITHOUT ANY WARRANTY; without even the implied warranty of  
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  
#  General Public License for more details.  
#  
#  You should have received a copy of the GNU General Public License  
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
##

# Includes of other scripts of toolbox set
. util								# Util functions and global variables
. backup							# Backup and restore functions
. cleaner							# Functions for cleaning


# este script so pode ser executado como root.
if [ "$(whoami)" != "root" ] ; then	
	_s=$(which sudo 2>/dev/null)		
	echo "This scrpt must be executed as root:"
	
	if [ -n "$_s" ] ; then
		sudo "$0" $@
	else
		su -c "'$0' $@"
	fi
	exit 0
fi


##
# FUNCTIONS
##
version(){
	echo "toolbox $VERSION"
    echo "Author: $AUTHOR"
}

usage(){
	version
    echo "syntax: $0 [OPTIONS] [PARAMS]"
    echo "  OPTIONS:"
    echo "    -h            					: Shows thes help"    
    echo "    -v          						: Shows the version"
    echo "    -b	PARENT_BACKUP_FOLDER        : Do a complete backup to a folder under PARENT_BACKUP_FOLDER"
    echo "    -r    RESTORE_FOLDER  			: Do a complete restore from RESTORE_FOLDER to a '/' directory"
    echo "    -c   								: Complete cleaning"
}



##
# MAIN LOOP
##
while getopts hvb:r: OPTION; do
	case "${OPTION}" in
		h) usage;;
		v) version;;
		b) backup ${OPTARG};;
		r) restore ${OPTARG};;
		*) usage ;;
	esac
done		

