#!/bin/sh
##
# File: util
# Author: Giovane Boaviagem <giovanebribeiro@gmail.com>
# Description: Utilities for toolbox scripts
# Since: 21/02/2013
#
#  This file is free software: you may copy, redistribute and/or modify it  
#  under the terms of the GNU General Public License as published by the  
#  Free Software Foundation, either version 2 of the License, or (at your  
#  option) any later version.  
#  
#  This file is distributed in the hope that it will be useful, but  
#  WITHOUT ANY WARRANTY; without even the implied warranty of  
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  
#  General Public License for more details.  
#  
#  You should have received a copy of the GNU General Public License  
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
##

# Global Variables
VERSION="1.0"
AUTHOR="Giovane Boaviagem"
LOG_FILE="/var/log/toolbox.log"
mail_content="/tmp/mail"

##
# log()
# @param $1 function name
# @param $2 log message
##
log(){
	echo -e "$2 " >> $mail_content
	echo -e "[$(date '+%d/%m/%Y %H:%M:%S')] $1: $2 " >> $LOG_FILE
}

##
# question()
##
question(){
    printf "\e[1;33m?? \e[1;37m$1 \e[1;30m[\e[1;32mS\e[1;30m/\e[1;31mN\e[1;30m]:\e[m "
    read out

    case "$out" in
        's' | 'S' )
            resp=1
            ;;
        * )
            resp=0
            ;;
    esac

    if [ "x$2" == "xecho" ]; then
        echo $resp
    else
        question=$resp
    fi

    return 0
}

##
# send_mail()
# @param $1 The e-mail address to send
##
send_mail(){
	addr=$1
	if [ ! -f "/usr/bin/mailx" ] ; then
		log "util" "You must have the heirloom-mailx package"
		return 1
	fi
	
	content=$(cat $mail_content)	
	echo $content | mailx -s "[TOOLBOX] $HOSTNAME -  Status Report" $1
}
