#!/bin/sh

##
# File: util
# Author: Giovane Boaviagem <giovanebribeiro@gmail.com># 
# Since: 21/02/2013
#
#  This file is free software: you may copy, redistribute and/or modify it  
#  under the terms of the GNU General Public License as published by the  
#  Free Software Foundation, either version 2 of the License, or (at your  
#  option) any later version.  
#  
#  This file is distributed in the hope that it will be useful, but  
#  WITHOUT ANY WARRANTY; without even the implied warranty of  
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  
#  General Public License for more details.  
#  
#  You should have received a copy of the GNU General Public License  
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
##

LOG_FILE="/var/log/toolbox.log"
mail_content="$PWD/toolbox.mail"

##
# log()
# @param $1 function name
# @param $2 log message
##
log(){
	echo -e "$2"
	echo -e "$2 " >> $mail_content
	echo -e "[$(date '+%d/%m/%Y %H:%M:%S')] $1: $2 " >> $LOG_FILE
}



##
# send_mail()
# @param $1 The e-mail address to send
##
send_mail(){
	addr=$1
	if [ ! -f "/usr/bin/mailx" ] ; then
		log "util" "You must have the heirloom-mailx package"
		return 1
	fi
	
	mailx -s "[TOOLBOX] $HOSTNAME -  Status Report" $1 < $mail_content

	rm $mail_content
}
