#!/bin/bash

##
# Provides virtual swap of 50% of RAM.
##
TAG="ZRAM"

start(){
	mem_total_kb=$(grep MemTotal /proc/meminfo | grep -E --only-matching '[[:digit:]]+')

	modprobe zram

	#only using 50% of system memory, comment the line below for 100%
	mem_total_kb=$((mem_total_kb/2))

	logger -t $TAG -s "Mem to be compresssed: $mem_total_kb" 

	echo $((mem_total_kb * 1024)) > /sys/block/zram0/disksize

	mkswap /dev/zram0

	swapon -p 100 /dev/zram0
}

stop(){
	swapoff /dev/zram0
	sleep 1
	rmmod zram
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 3
		start
		;;
	*)
		logger -t $TAG -s "Usage: $0 {start|stop|restart}"
		;;
esac
