#!/bin/bash

##
# File: backup_raspberry
# Description: Backup script for Raspberry Pi. Creates a image in external storage.
# Date: 16/01/2014
##

##
# Configs
##
# Backup's image directory
DST=/home/giovane/hd/backup/cotoco
PUSHOVER_DIR=/home/giovane/scripts/raspberry











##
# Not change behind this point...
##
# Nome do arquivo de imagem(sera' complementado com a data):
FILENAME=backup_
NOW=$(date +%d-%m-%Y)
TAG="BACKUP"
MSG1="Procedimentos de backup [1/4]: Desligando os daemons."
MSG2="Procedimentos de backup [2/4]: Verificando a pasta de backup."
MSG3="Procedimentos de backup [3/4]: Criando o arquivo de backup."
MSG4="Procedimentos de backup [4/4]: Reiniciando o sistema."

logger -t $TAG -s $MSG1
/bin/bash $PUSHOVER_DIR/pushover.sh sd cotoco "Cotoco" "$MSG1"
systemctl daemon-reload
sleep 5
systemctl stop smbd nmbd
sleep 5
systemctl stop transmission
sleep 5
systemctl stop btsync
sleep 5
systemctl stop cronie
sleep 10

logger -t $TAG -s $MSG2
/bin/bash $PUSHOVER_DIR/pushover.sh sd cotoco "Cotoco" "$MSG2"
if [ ! -d $DST ] ; then
        logger -t $TAG -s "$DST nao existe. Criando..."
        mkdir -p $DST
fi
cd $DST
rm *.img
sleep 10

logger -t $TAG -s $MSG3
/bin/bash $PUSHOVER_DIR/pushover.sh sd cotoco "Cotoco" "$MSG3"
dd bs=1M if=/dev/mmcblk0 of=$DST/$FILENAME$NOW.img
sleep 10

logger -t $TAG -s $MSG4
/bin/bash $PUSHOVER_DIR/pushover.sh sd cotoco "Cotoco" "$MSG4"
sleep 10
reboot

